### ISSUE TITLE
Publish Dokka generated API documentation

### ISSUE THREAD

**Issue by CommanderTvis** [JetBrains-Research/viktor#46]

**Comment by dievsky** [comment]
Publish it where? We have javadoc on Maven Central.

**Comment by CommanderTvis** [comment]
For example, on GitHub pages

**Comment by CommanderTvis** [comment]
Example configuration for Github Actions:
```yaml
name: Dokka publication

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.1.0
          java: java11
          arch: amd64
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ubuntu-20.04-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ubuntu-20.04-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew dokkaHtml --no-daemon --no-parallel --stacktrace
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build/dokka/html
```
